@API_URL = https://stugmaklaren.azurewebsites.net/

@Local_URL = http://localhost:3030

# Service ID (insert ID here to change 
@Service_Id = 2

# Insert service date here (YYYY-MM-DD)
@Service_Date = 2022-12-24

### Post an order

POST {{Local_URL}}/orders
Content-Type: application/json

{
        "date": "2022-12-24",
        "cabin": "Cabin 1",
        "service": "Städa WC och Bastu"
}

### Get orders

GET {{Local_URL}}/orders

### Get orders with a date

GET {{Local_URL}}/orders?date={{Service_Date}}

### Get a order with specific ID

GET {{Local_URL}}/orders/{{Service_Id}}

### Update a order

PUT {{Local_URL}}/orders/{{Service_Id}}
Content-Type: application/json

{
        "service": "Städa WC och Bastu 2",
        "date": "2022-12-23"
}

### Delete order by specific ID

DELETE {{Local_URL}}/orders/{{Service_Id}}
