@API_URL = https://stugmaklaren.azurewebsites.net/

@API_Service = https://stugtjansterab.azurewebsites.net

@API_Local = http://localhost:3030

# Service ID (insert ID here to change 
@Service_Id = 2

# Insert service date here (YYYY-MM-DD)
@Service_Date = 2022-12-24

### Post an order

POST {{API_Service}}/orders
Content-Type: application/json

{
        "date": "2022-12-24",
        "cabin": "Villa Ballabulla",
        "service": "Städa WC och Bastu"
}

### Get orders

GET {{API_Service}}/orders

### Get orders with a date

GET {{API_Service}}/orders?date={{Service_Date}}

### Get a order with specific ID

GET {{API_Service}}/orders/{{Service_Id}}

### Update a order

PUT {{API_Service}}/orders/{{Service_Id}}
Content-Type: application/json

{
        "service": "Städa WC och Bastu 2",
        "date": "2022-12-23"
}

### Delete order by specific ID

DELETE {{API_Service}}/orders/{{Service_Id}}
