@API_URL = https://stugmaklaren.azurewebsites.net/

@Local_URL = http://localhost:3030

# TODO: change to an existing service ID
@Service_Id = 1

### Posta en service

POST {{Local_URL}}/services
Content-Type: application/json

{
        "service": "Städa WC och Bastu",
        "description": "Städa både WC och Bastun. Allt skuras"
}

### Get services

GET {{Local_URL}}/services

### Get a service with specific ID

GET {{Local_URL}}/services/{{Service_Id}}

### Update a service

PUT {{Local_URL}}/services/{{Service_Id}}
Content-Type: application/json

{
        "service": "Städa WC och Bastu 2",
        "description": "Städa både WC och Bastun. Allt skuras"
}

### Delete service by specific ID

DELETE {{Local_URL}}/orders/{{Service_Id}}