@API_URL = https://stugmaklaren.azurewebsites.net/

@Local_URL = http://localhost:3030

### Posta en service

POST {{Local_URL}}/services
Content-Type: application/json

{
        "service": "Städa WC och Bastu",
        "description": "Städa både WC och Bastun. Allt skuras"
}
